TOPLEVEL_LANG ?= verilog
SIM ?= icarus
VERILOG_SOURCES = $(shell pwd)/count-ones.sv
TOPLEVEL := count_ones # Verilog or SystemVerilog TOP file module name
MODULE   := count-ones-tb # Python file name


include $(shell cocotb-config --makefiles)/Makefile.sim